### ISSUE TITLE
有deb包嘛？

### ISSUE THREAD

**Issue by liuzjccc** [tangyibo/greenplum_exporter#1]
有deb包嘛？

**Comment by tangyibo** [comment]
您可以通过如下的docker容器方式部署：
docker run -d -p 9297:9297 -e GPDB_DATA_SOURCE_URL=postgres://gpadmin:gpadmin@10.17.20.11:5432/postgres?sslmode=disable  inrgihc/greenplum6-exporter:latest 
其中,环境变量GPDB_DATA_SOURCE_URL为使用gpadmin账号连接greenplum6数据库的连接字符串
