### ISSUE TITLE
监控数据有断点

### ISSUE THREAD

**Issue by hebaodanroot** [tangyibo/greenplum_exporter#11]
![image](https://user-images.githubusercontent.com/45256479/106697140-28396e00-6619-11eb-8e11-39fc8b05af75.png)
日志
![image](https://user-images.githubusercontent.com/45256479/106697202-4010f200-6619-11eb-8bd7-34a1cc8bbea9.png)

**Comment by hebaodanroot** [comment]
> ![image](https://user-images.githubusercontent.com/45256479/106697140-28396e00-6619-11eb-8e11-39fc8b05af75.png)
> 日志
> ![image](https://user-images.githubusercontent.com/45256479/106697202-4010f200-6619-11eb-8bd7-34a1cc8bbea9.png)

**Comment by hebaodanroot** [comment]
> ![image](https://user-images.githubusercontent.com/45256479/106697140-28396e00-6619-11eb-8e11-39fc8b05af75.png)
> 日志
> ![image](https://user-images.githubusercontent.com/45256479/106697202-4010f200-6619-11eb-8bd7-34a1cc8bbea9.png)

**Comment by hebaodanroot** [comment]
![image](https://user-images.githubusercontent.com/45256479/106698020-ead5e000-661a-11eb-95e0-d86c328ddddc.png)
![image](https://user-images.githubusercontent.com/45256479/106698041-f6290b80-661a-11eb-8ffb-c1f870196962.png)

**Comment by tangyibo** [comment]
当greenplum_exporter服务无法正常连接上Greenplum数据库时，会导致数据无法正常采集。至于greenplum_exporter服务无法正常连接上Greenplum的原因可能由于网络问题、Greenplum数据库连接数已满造成的无法连接等。可以通过如下命令查询greenplum_exporter服务的错误日志信息：
```
[root@localhost ~]# journalctl -u greenplum_exporter.service -f
```
希望，以上方法能够对您有所帮助！

**Comment by hebaodanroot** [comment]
> ```
>    当greenplum_exporter服务无法正常连接上Greenplum数据库时，会导致数据无法正常采集。至于greenplum_exporter服务无法正常连接上Greenplum的原因可能由于网络问题、Greenplum数据库连接数已满造成的无法连接等。
> 
>    通过您图上的日志信息，感觉您的greenplum_exporter程序有运行时错误，不是最新稳定版本程序，可尝试更新下程序试试！
> 
>    希望以上方法能够对您有所帮助！
> ```
你好我现在换成这个采集器好几天没有断点了，也是基于你的开发的呀
https://github.com/ChrisYuan/greenplum_exporter
