### ISSUE TITLE
各数据库表数量不正确

### ISSUE THREAD

**Issue by Danpilz** [tangyibo/greenplum_exporter#12]
GP版本：6.3
GP_exporter：1.1
你好，我配置的test库连接，但其他数据库的表数量都是test库的表数量，如何解决？
![image](https://user-images.githubusercontent.com/35871541/109918692-60080400-7cf2-11eb-9267-03862164b362.png)
![image](https://user-images.githubusercontent.com/35871541/109918702-6302f480-7cf2-11eb-9080-a06a9d4fdb7c.png)

**Comment by tangyibo** [comment]
您好，您的GP连接字符串配置有误，数据库名称必须为postgres，即：
```
GPDB_DATA_SOURCE_URL=postgres://gpadmin:gpadmin1@127.0.0.1:5432/postgres?sslmode=disable
```
