### ISSUE TITLE
安装成功后，无法访问监控页面，报错

### ISSUE THREAD

**Issue by csj1025** [tangyibo/greenplum_exporter#2]
我在linux环境编译启动成功后，访问9297/metrics页面报错，这是什么问题啊
![image](https://user-images.githubusercontent.com/26039841/99510641-47cddc80-29c2-11eb-9927-9bfcafe5ea5b.png)

**Comment by tangyibo** [comment]
您好，只支持Greenplum6版本，不支持Greenplum5及其以下版本！
