### ISSUE TITLE
exporter连接问题

### ISSUE THREAD

**Issue by laoxiaokang** [tangyibo/greenplum_exporter#24]
在docker容器中运行该命令
```
 docker run -d -p 9297:9297 --name gp_exporter  -e GPDB_DATA_SOURCE_URL=postgres://gpadmin:LcGp\!2345@10.110.74.58:5432/postgres?sslmode=disable  docker.io/inrgihc/greenplum_exporter:1.1
```
报错:
time="2021-10-20T09:27:57Z" level=error msg="check database connection failed, error:pq: syntax error at or near \"[\"" source="collector.go:83"
请问是哪里的问题，求大神解答

**Comment by cobolbaby** [comment]
密码里面含有特殊字符，你确定不需要转义？
