### ISSUE TITLE
Confirm your license.

### ISSUE THREAD

**Issue by david-stdio** [tangyibo/greenplum_exporter#33]
Hello, I'm a DBA at Kakao in Korea. I implemented a greenplum exporter to monitor Greenplum, and our next step was to make our code open-source.         
However, I noticed that many aspects of our code have similarities with this GitHub snippet, because queries in our code and the exporter implementation are based on Greenplum and Prometheus, respectively. We'd like to reconfirm that there's no license of your code, you've noted in the LICENSE file. Please confirm if we can use freely.
We are looking forward to your reply. 
Thank you.

**Comment by tangyibo** [comment]
yes, you can use it freely if you make your code open-source.

**Comment by tangyibo** [comment]
close
