### ISSUE TITLE
已经正常部署，数据膨胀和数据倾斜没监控项没有数据

### ISSUE THREAD

**Issue by hebaodanroot** [tangyibo/greenplum_exporter#5]
grafana 版本6.6.2
gp版本 6.11.1
![image](https://user-images.githubusercontent.com/45256479/103279261-59b28e80-4a08-11eb-87d1-fc62feb11e0d.png)

**Comment by tangyibo** [comment]
先前的greenplum_grafana.json文件有误，已经做了更新，请到release页面下载最新文件，并更新到grafana中

**Comment by hebaodanroot** [comment]
谢谢

**Comment by Alex-wwei** [comment]
最新版的没有数据倾斜和膨胀的指标数据啊，grafana大屏也没显示。是去掉了？
